
import { Language, Currency, Category, AccountType } from './types';

export const SUPPORTED_CURRENCIES: Currency[] = ['USD', 'EUR', 'COP', 'MXN', 'GBP'];

export const FLAGS: Record<Currency, string> = {
  USD: '🇺🇸',
  EUR: '🇪🇺',
  COP: '🇨🇴',
  MXN: '🇲🇽',
  GBP: '🇬🇧',
};

// Smart Categorization Keywords
export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  'cat_transport': ['uber', 'taxi', 'bus', 'tren', 'metro', 'gasolina', 'fuel', 'peaje', 'lyft', 'cabify', 'did'],
  'cat_food': ['mcdonalds', 'burger', 'pizza', 'sushi', 'restaurante', 'kfc', 'starbucks', 'cafe', 'coffee', 'lunch', 'dinner', 'taco'],
  'cat_shopping': ['amazon', 'walmart', 'target', 'zara', 'nike', 'adidas', 'ropa', 'clothes', 'shoes', 'tienda', 'market', 'supermercado'],
  'cat_entertainment': ['netflix', 'spotify', 'hbo', 'disney', 'cine', 'movie', 'cinema', 'juego', 'game', 'steam', 'playstation', 'xbox'],
  'cat_utilities': ['luz', 'agua', 'gas', 'internet', 'wifi', 'telefono', 'celular', 'phone', 'bill', 'factura', 'electricidad'],
  'cat_housing': ['alquiler', 'rent', 'hipoteca', 'mortgage', 'casa', 'home', 'mantenimiento'],
  'cat_health': ['farmacia', 'pharmacy', 'doctor', 'medico', 'hospital', 'dentista', 'salud', 'gym', 'gimnasio'],
  'cat_salary': ['nomina', 'salary', 'sueldo', 'pago', 'payroll'],
};

export const ACCOUNT_TYPES: AccountType[] = ['cash', 'checking', 'savings', 'credit_card', 'investment'];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: '1', key: 'cat_salary', icon: 'Briefcase', color: 'bg-green-100 text-green-600', type: 'income' },
  { id: '2', key: 'cat_freelance', icon: 'Laptop', color: 'bg-blue-100 text-blue-600', type: 'income' },
  { id: '3', key: 'cat_gift', icon: 'Gift', color: 'bg-purple-100 text-purple-600', type: 'income' },
  { id: '4', key: 'cat_investment', icon: 'TrendingUp', color: 'bg-emerald-100 text-emerald-600', type: 'income' },
  { id: '5', key: 'cat_food', icon: 'Utensils', color: 'bg-orange-100 text-orange-600', type: 'expense' },
  { id: '6', key: 'cat_transport', icon: 'Car', color: 'bg-blue-100 text-blue-600', type: 'expense' },
  { id: '7', key: 'cat_utilities', icon: 'Zap', color: 'bg-yellow-100 text-yellow-600', type: 'expense' },
  { id: '8', key: 'cat_entertainment', icon: 'Film', color: 'bg-pink-100 text-pink-600', type: 'expense' },
  { id: '9', key: 'cat_shopping', icon: 'ShoppingBag', color: 'bg-indigo-100 text-indigo-600', type: 'expense' },
  { id: '10', key: 'cat_health', icon: 'Heart', color: 'bg-red-100 text-red-600', type: 'expense' },
  { id: '11', key: 'cat_education', icon: 'BookOpen', color: 'bg-teal-100 text-teal-600', type: 'expense' },
  { id: '12', key: 'cat_housing', icon: 'Home', color: 'bg-stone-100 text-stone-600', type: 'expense' },
  { id: '13', key: 'cat_other', icon: 'MoreHorizontal', color: 'bg-gray-100 text-gray-600', type: 'expense' },
];

export const TRANSLATIONS = {
  es: {
    // General
    greeting_morning: 'Buenos días,',
    greeting_afternoon: 'Buenas tardes,',
    greeting_evening: 'Buenas noches,',
    continue: 'Continuar',
    save: 'Guardar',
    delete: 'Eliminar',
    undo: 'Deshacer',
    deleted: 'Registro eliminado',
    cancel: 'Cancelar',
    settings: 'Ajustes',
    history: 'Historial',
    search: 'Buscar...',
    
    // Tabs & Headers
    tab_balance: 'Balance',
    tab_goals: 'Metas',
    tab_debts: 'Deudas',
    total_balance: 'Balance Total',
    my_accounts: 'Mis Cuentas',
    recent_activity: 'Movimientos',
    your_goals: 'Tus Objetivos',
    
    // Entities
    account: 'Cuenta',
    goal: 'Meta',
    debt: 'Deuda',
    new_record: 'Nuevo Registro',
    add_account: 'Añadir Cuenta',
    add_goal: 'Añadir Meta',
    add_debt: 'Añadir Persona',
    edit_account: 'Editar Cuenta',
    edit_goal: 'Editar Meta',
    edit_debt: 'Editar Deuda',
    
    // Account Types
    type_cash: 'Efectivo',
    type_checking: 'Cuenta Corriente',
    type_savings: 'Cuenta de Ahorros',
    type_credit_card: 'Tarjeta de Crédito',
    type_investment: 'Inversión',

    // Fields
    amount: 'Monto',
    concept: 'Concepto',
    description: 'Descripción',
    category: 'Categoría',
    type: 'Tipo',
    date: 'Fecha',
    target: 'Objetivo',
    current_saved: 'Ahorrado Actual',
    initial_balance: 'Saldo Inicial',
    icon_label: 'Icono',
    goal_name: 'Nombre de la Meta',
    debt_person: 'Persona',
    owe_me: 'Me deben',
    i_owe: 'Debo',
    missing: 'Faltan',
    completed: 'Completado',
    
    // Transaction Types
    income: 'Ingreso',
    expense: 'Gasto',
    transfer: 'Transferencia',
    
    // Recurring
    active_rules: 'Reglas Activas',
    no_recurring: 'No hay transacciones recurrentes.',
    is_recurring: 'Hacer recurrente',
    recurring_suggestion: 'Sugerencia: Parece un gasto mensual.',
    frequency: 'Frecuencia',
    notify_me: 'Notificarme',
    freq_daily: 'Diario',
    freq_weekly: 'Semanal',
    freq_monthly: 'Mensual',
    freq_yearly: 'Anual',
    
    // Interest Feature
    advanced_options: 'Opciones Avanzadas',
    enable_interest: 'Generar Intereses',
    interest_rate: 'Tasa (%)',
    compounding: 'Capitalización',
    int_daily: 'Diaria',
    int_weekly: 'Semanal',
    int_monthly: 'Mensual',
    int_yearly: 'Anual',
    start_date: 'Fecha de Inicio',
    capital: 'Capital',
    interest: 'Interés',

    // Filters & Reports
    filters: 'Filtros',
    date_range: 'Fechas',
    from: 'Desde',
    to: 'Hasta',
    all_time: 'Todo el tiempo',
    entity_type: 'Mostrar', // Humanized
    all_entities: 'Todo', // Humanized
    all_accounts: 'Solo Cuentas', // Humanized
    all_goals: 'Solo Metas', // Humanized
    all_debts: 'Solo Deudas', // Humanized
    specific_item: 'Seleccionar...', // Humanized
    balance_evolution: 'Evolución del Dinero',
    distribution: 'Distribución de Gastos',
    clear_dates: 'Limpiar',
    spending_pace: 'Ritmo de Gasto',
    safe_pace: 'Ritmo Saludable',
    warning_pace: 'Gasto Acelerado',

    // Notifications & Alerts
    notifications: 'Notificaciones',
    notify_low_balance: 'Balance Bajo',
    notify_debts: 'Recordatorio de Deudas',
    notify_goals: 'Hitos de Metas',
    threshold: 'Umbral',
    alert_low_balance: '¡Alerta de balance bajo!',
    alert_debt_due: 'Vencimiento de deuda cercano:',
    alert_goal_milestone: '¡Felicidades! Hito alcanzado:',
    alert_recurring_processed: 'Transacción recurrente procesada:',

    // Onboarding
    welcome_title: 'Bienvenido a Cuentas Claras',
    name_placeholder: '¿Cómo te gustaría que te llamemos?',
    select_currency_title: 'Selecciona tu moneda',
    setup_first_title: 'Vamos a crear tu primer registro',
    setup_subtitle: 'Puedes crear una cuenta, una meta o registrar una deuda.',
    setup_skip: 'Omitir',
    create_finish: 'Crear y Finalizar',
    
    // Settings & Reports
    theme: 'Tema',
    theme_light: 'Claro',
    theme_dark: 'Oscuro',
    theme_system: 'Sistema',
    language: 'Idioma',
    currency: 'Divisa Principal',
    feedback: 'Calificar App',
    reports: 'Reportes',
    data_management: 'Gestión de Datos',
    export_data: 'Exportar Datos',
    import_data: 'Importar Datos',
    expenses_by_category: 'Gastos por Categoría',
    view_list: 'Lista',
    view_chart: 'Gráficas',
    no_transactions: 'No hay transacciones recientes',
    
    // Categories
    cat_salary: 'Salario',
    cat_freelance: 'Freelance',
    cat_gift: 'Regalo',
    cat_investment: 'Inversión',
    cat_food: 'Comida',
    cat_transport: 'Transporte',
    cat_utilities: 'Servicios',
    cat_entertainment: 'Entretenimiento',
    cat_shopping: 'Compras',
    cat_health: 'Salud',
    cat_education: 'Educación',
    cat_housing: 'Vivienda',
    cat_other: 'Otros',
  },
  en: {
    greeting_morning: 'Good morning,',
    greeting_afternoon: 'Good afternoon,',
    greeting_evening: 'Good evening,',
    continue: 'Continue',
    save: 'Save',
    delete: 'Delete',
    undo: 'Undo',
    deleted: 'Record deleted',
    cancel: 'Cancel',
    settings: 'Settings',
    history: 'History',
    search: 'Search...',
    
    tab_balance: 'Balance',
    tab_goals: 'Goals',
    tab_debts: 'Debts',
    total_balance: 'Total Balance',
    my_accounts: 'My Accounts',
    recent_activity: 'Recent Activity',
    your_goals: 'Your Goals',
    
    account: 'Account',
    goal: 'Goal',
    debt: 'Debt',
    new_record: 'New Record',
    add_account: 'Add Account',
    add_goal: 'Add Goal',
    add_debt: 'Add Person',
    edit_account: 'Edit Account',
    edit_goal: 'Edit Goal',
    edit_debt: 'Edit Debt',
    
    type_cash: 'Cash',
    type_checking: 'Checking Account',
    type_savings: 'Savings Account',
    type_credit_card: 'Credit Card',
    type_investment: 'Investment',

    amount: 'Amount',
    concept: 'Title',
    description: 'Description',
    category: 'Category',
    type: 'Type',
    date: 'Date',
    target: 'Target',
    current_saved: 'Currently Saved',
    initial_balance: 'Initial Balance',
    icon_label: 'Icon',
    goal_name: 'Goal Name',
    debt_person: 'Person',
    owe_me: 'Owed to me',
    i_owe: 'I owe',
    missing: 'Remaining',
    completed: 'Completed',
    
    income: 'Income',
    expense: 'Expense',
    transfer: 'Transfer',
    
    active_rules: 'Active Rules',
    no_recurring: 'No recurring transactions found.',
    is_recurring: 'Make Recurring',
    recurring_suggestion: 'Suggestion: Looks like a monthly expense.',
    frequency: 'Frequency',
    notify_me: 'Notify me',
    freq_daily: 'Daily',
    freq_weekly: 'Weekly',
    freq_monthly: 'Monthly',
    freq_yearly: 'Yearly',
    
    advanced_options: 'Advanced Options',
    enable_interest: 'Enable Interest',
    interest_rate: 'Rate (%)',
    compounding: 'Compounding',
    int_daily: 'Daily',
    int_weekly: 'Weekly',
    int_monthly: 'Monthly',
    int_yearly: 'Yearly',
    start_date: 'Start Date',
    capital: 'Principal',
    interest: 'Interest',

    filters: 'Filters',
    date_range: 'Date Range',
    from: 'From',
    to: 'To',
    all_time: 'All Time',
    entity_type: 'Show',
    all_entities: 'Everything',
    all_accounts: 'Accounts Only',
    all_goals: 'Goals Only',
    all_debts: 'Debts Only',
    specific_item: 'Select...',
    balance_evolution: 'Balance Evolution',
    distribution: 'Spending Distribution',
    clear_dates: 'Clear',
    spending_pace: 'Spending Rhythm',
    safe_pace: 'Safe Pace',
    warning_pace: 'High Spending',

    notifications: 'Notifications',
    notify_low_balance: 'Low Balance',
    notify_debts: 'Debt Reminders',
    notify_goals: 'Goal Milestones',
    threshold: 'Threshold',
    alert_low_balance: 'Low balance alert!',
    alert_debt_due: 'Debt due soon:',
    alert_goal_milestone: 'Congrats! Goal milestone:',
    alert_recurring_processed: 'Recurring transaction processed:',

    welcome_title: 'Welcome to Clear Accounts',
    name_placeholder: 'What should we call you?',
    select_currency_title: 'Select your currency',
    setup_first_title: 'Let\'s create your first record',
    setup_subtitle: 'You can create an account, a goal, or track a debt.',
    setup_skip: 'Skip',
    create_finish: 'Create & Finish',
    
    theme: 'Theme',
    theme_light: 'Light',
    theme_dark: 'Dark',
    theme_system: 'System',
    language: 'Language',
    currency: 'Main Currency',
    feedback: 'Rate App',
    reports: 'Reports',
    data_management: 'Data Management',
    export_data: 'Export Data',
    import_data: 'Import Data',
    expenses_by_category: 'Expenses by Category',
    view_list: 'List',
    view_chart: 'Analytics',
    no_transactions: 'No recent transactions',
    
    cat_salary: 'Salary',
    cat_freelance: 'Freelance',
    cat_gift: 'Gift',
    cat_investment: 'Investment',
    cat_food: 'Food',
    cat_transport: 'Transport',
    cat_utilities: 'Utilities',
    cat_entertainment: 'Entertainment',
    cat_shopping: 'Shopping',
    cat_health: 'Health',
    cat_education: 'Education',
    cat_housing: 'Housing',
    cat_other: 'Other',
  },
  fr: {
    greeting_morning: 'Bonjour,',
    greeting_afternoon: 'Bon après-midi,',
    greeting_evening: 'Bonsoir,',
    continue: 'Continuer',
    save: 'Enregistrer',
    delete: 'Supprimer',
    undo: 'Annuler',
    deleted: 'Enregistrement supprimé',
    cancel: 'Annuler',
    settings: 'Réglages',
    history: 'Historique',
    search: 'Rechercher...',
    
    tab_balance: 'Solde',
    tab_goals: 'Objectifs',
    tab_debts: 'Dettes',
    total_balance: 'Solde Total',
    my_accounts: 'Mes Comptes',
    recent_activity: 'Activité Récente',
    your_goals: 'Vos Objectifs',
    
    account: 'Compte',
    goal: 'Objectif',
    debt: 'Dette',
    new_record: 'Nouveau',
    add_account: 'Ajouter',
    add_goal: 'Ajouter Objectif',
    add_debt: 'Ajouter Personne',
    edit_account: 'Modifier Compte',
    edit_goal: 'Modifier Objectif',
    edit_debt: 'Modifier Dette',
    
    type_cash: 'Espèces',
    type_checking: 'Compte Courant',
    type_savings: 'Compte Épargne',
    type_credit_card: 'Carte de Crédit',
    type_investment: 'Investissement',

    amount: 'Montant',
    concept: 'Titre',
    description: 'Description',
    category: 'Catégorie',
    type: 'Type',
    date: 'Date',
    target: 'Cible',
    current_saved: 'Actuellement épargné',
    initial_balance: 'Solde Initial',
    icon_label: 'Icône',
    goal_name: 'Nom de l\'objectif',
    debt_person: 'Personne',
    owe_me: 'On me doit',
    i_owe: 'Je dois',
    missing: 'Restant',
    completed: 'Terminé',
    
    income: 'Revenu',
    expense: 'Dépense',
    transfer: 'Virement',
    
    active_rules: 'Règles Actives',
    no_recurring: 'Aucune transaction récurrente.',
    is_recurring: 'Rendre récurrent',
    recurring_suggestion: 'Suggestion : Semble être mensuel.',
    frequency: 'Fréquence',
    notify_me: 'Avertissez-moi',
    freq_daily: 'Quotidien',
    freq_weekly: 'Hebdomadaire',
    freq_monthly: 'Mensuel',
    freq_yearly: 'Annuel',
    
    advanced_options: 'Options Avancées',
    enable_interest: 'Activer les Intérêts',
    interest_rate: 'Taux (%)',
    compounding: 'Capitalisation',
    int_daily: 'Journalier',
    int_weekly: 'Hebdomadaire',
    int_monthly: 'Mensuel',
    int_yearly: 'Annuel',
    start_date: 'Date de début',
    capital: 'Capital',
    interest: 'Intérêt',

    filters: 'Filtres',
    date_range: 'Plage de dates',
    from: 'De',
    to: 'À',
    all_time: 'Tout le temps',
    entity_type: 'Afficher',
    all_entities: 'Tout',
    all_accounts: 'Comptes',
    all_goals: 'Objectifs',
    all_debts: 'Dettes',
    specific_item: 'Sélectionner...',
    balance_evolution: 'Évolution du solde',
    distribution: 'Distribution',
    clear_dates: 'Effacer',
    spending_pace: 'Rythme de dépense',
    safe_pace: 'Rythme sûr',
    warning_pace: 'Dépense élevée',
    
    notifications: 'Notifications',
    notify_low_balance: 'Solde Bas',
    notify_debts: 'Rappel de Dettes',
    notify_goals: 'Étapes Objectifs',
    threshold: 'Seuil',
    alert_low_balance: 'Alerte de solde bas !',
    alert_debt_due: 'Dette à payer bientôt :',
    alert_goal_milestone: 'Bravo ! Étape atteinte :',
    alert_recurring_processed: 'Transaction récurrente traitée :',

    welcome_title: 'Bienvenue',
    name_placeholder: 'Comment devons-nous vous appeler ?',
    select_currency_title: 'Sélectionnez votre devise',
    setup_first_title: 'Créons votre premier enregistrement',
    setup_subtitle: 'Vous pouvez créer un compte, un objectif ou une dette.',
    setup_skip: 'Passer',
    create_finish: 'Créer et Terminer',
    
    theme: 'Thème',
    theme_light: 'Clair',
    theme_dark: 'Sombre',
    theme_system: 'Système',
    language: 'Langue',
    currency: 'Devise',
    feedback: 'Noter l\'app',
    reports: 'Rapports',
    data_management: 'Gestion des Données',
    export_data: 'Exporter',
    import_data: 'Importer',
    expenses_by_category: 'Dépenses par Catégorie',
    view_list: 'Liste',
    view_chart: 'Graphiques',
    no_transactions: 'Aucune transaction',
    
    cat_salary: 'Salaire',
    cat_freelance: 'Freelance',
    cat_gift: 'Cadeau',
    cat_investment: 'Investissement',
    cat_food: 'Nourriture',
    cat_transport: 'Transport',
    cat_utilities: 'Utilitaires',
    cat_entertainment: 'Divertissement',
    cat_shopping: 'Shopping',
    cat_health: 'Santé',
    cat_education: 'Éducation',
    cat_housing: 'Logement',
    cat_other: 'Autre',
  },
  pt: {
    greeting_morning: 'Bom dia,',
    greeting_afternoon: 'Boa tarde,',
    greeting_evening: 'Boa noite,',
    continue: 'Continuar',
    save: 'Salvar',
    delete: 'Excluir',
    undo: 'Desfazer',
    deleted: 'Registro excluído',
    cancel: 'Cancelar',
    settings: 'Ajustes',
    history: 'Histórico',
    search: 'Buscar...',
    
    tab_balance: 'Saldo',
    tab_goals: 'Metas',
    tab_debts: 'Dívidas',
    total_balance: 'Saldo Total',
    my_accounts: 'Minhas Contas',
    recent_activity: 'Atividade Recente',
    your_goals: 'Seus Objetivos',
    
    account: 'Conta',
    goal: 'Meta',
    debt: 'Dívida',
    new_record: 'Novo Registro',
    add_account: 'Adicionar Conta',
    add_goal: 'Adicionar Meta',
    add_debt: 'Adicionar Pessoa',
    edit_account: 'Editar Conta',
    edit_goal: 'Editar Meta',
    edit_debt: 'Editar Dívida',
    
    type_cash: 'Dinheiro',
    type_checking: 'Conta Corrente',
    type_savings: 'Poupança',
    type_credit_card: 'Cartão de Crédito',
    type_investment: 'Investimento',

    amount: 'Valor',
    concept: 'Título',
    description: 'Descrição',
    category: 'Categoria',
    type: 'Tipo',
    date: 'Data',
    target: 'Alvo',
    current_saved: 'Economizado Atual',
    initial_balance: 'Saldo Inicial',
    icon_label: 'Ícone',
    goal_name: 'Nome da Meta',
    debt_person: 'Pessoa',
    owe_me: 'Me devem',
    i_owe: 'Devo',
    missing: 'Faltam',
    completed: 'Concluído',
    
    income: 'Receita',
    expense: 'Despesa',
    transfer: 'Transferência',
    
    active_rules: 'Regras Ativas',
    no_recurring: 'Nenhuma transação recorrente.',
    is_recurring: 'Tornar Recorrente',
    recurring_suggestion: 'Sugestão: Parece mensal.',
    frequency: 'Frequência',
    notify_me: 'Notifique-me',
    freq_daily: 'Diário',
    freq_weekly: 'Semanal',
    freq_monthly: 'Mensal',
    freq_yearly: 'Anual',
    
    advanced_options: 'Opções Avançadas',
    enable_interest: 'Habilitar Juros',
    interest_rate: 'Taxa (%)',
    compounding: 'Capitalização',
    int_daily: 'Diária',
    int_weekly: 'Semanal',
    int_monthly: 'Mensal',
    int_yearly: 'Anual',
    start_date: 'Data de Início',
    capital: 'Principal',
    interest: 'Juros',
    
    filters: 'Filtros',
    date_range: 'Intervalo de datas',
    from: 'De',
    to: 'Até',
    all_time: 'Todo o tempo',
    entity_type: 'Exibir',
    all_entities: 'Tudo',
    all_accounts: 'Só Contas',
    all_goals: 'Só Metas',
    all_debts: 'Só Dívidas',
    specific_item: 'Selecionar...',
    balance_evolution: 'Evolução do Saldo',
    distribution: 'Distribuição',
    clear_dates: 'Limpar',
    spending_pace: 'Ritmo de Gastos',
    safe_pace: 'Ritmo Seguro',
    warning_pace: 'Gasto Alto',

    notifications: 'Notificações',
    notify_low_balance: 'Saldo Baixo',
    notify_debts: 'Lembrete de Dívidas',
    notify_goals: 'Marcos de Metas',
    threshold: 'Limite',
    alert_low_balance: 'Alerta de saldo baixo!',
    alert_debt_due: 'Dívida vencendo em breve:',
    alert_goal_milestone: 'Parabéns! Meta alcançada:',
    alert_recurring_processed: 'Transação recorrente processada:',

    welcome_title: 'Bem-vindo ao Contas Claras',
    name_placeholder: 'Como devemos chamá-lo?',
    select_currency_title: 'Selecione sua moeda',
    setup_first_title: 'Vamos criar seu primeiro registro',
    setup_subtitle: 'Você pode criar uma conta, uma meta ou registrar uma dívida.',
    setup_skip: 'Pular',
    create_finish: 'Criar e Finalizar',
  },
};
