import { Language, Currency, Category } from './types';

export const SUPPORTED_CURRENCIES: Currency[] = ['USD', 'EUR', 'COP', 'MXN', 'GBP'];

export const DEFAULT_CATEGORIES: Category[] = [
  { id: '1', key: 'cat_salary', icon: 'Briefcase', color: 'bg-green-100 text-green-600', type: 'income' },
  { id: '2', key: 'cat_freelance', icon: 'Laptop', color: 'bg-blue-100 text-blue-600', type: 'income' },
  { id: '3', key: 'cat_gift', icon: 'Gift', color: 'bg-purple-100 text-purple-600', type: 'income' },
  { id: '4', key: 'cat_investment', icon: 'TrendingUp', color: 'bg-emerald-100 text-emerald-600', type: 'income' },
  { id: '5', key: 'cat_food', icon: 'Utensils', color: 'bg-orange-100 text-orange-600', type: 'expense' },
  { id: '6', key: 'cat_transport', icon: 'Car', color: 'bg-blue-100 text-blue-600', type: 'expense' },
  { id: '7', key: 'cat_utilities', icon: 'Zap', color: 'bg-yellow-100 text-yellow-600', type: 'expense' },
  { id: '8', key: 'cat_entertainment', icon: 'Film', color: 'bg-pink-100 text-pink-600', type: 'expense' },
  { id: '9', key: 'cat_shopping', icon: 'ShoppingBag', color: 'bg-indigo-100 text-indigo-600', type: 'expense' },
  { id: '10', key: 'cat_health', icon: 'Heart', color: 'bg-red-100 text-red-600', type: 'expense' },
  { id: '11', key: 'cat_education', icon: 'BookOpen', color: 'bg-teal-100 text-teal-600', type: 'expense' },
  { id: '12', key: 'cat_housing', icon: 'Home', color: 'bg-stone-100 text-stone-600', type: 'expense' },
  { id: '13', key: 'cat_other', icon: 'MoreHorizontal', color: 'bg-gray-100 text-gray-600', type: 'expense' },
];

export const TRANSLATIONS = {
  es: {
    greeting_morning: 'Buenos días,',
    greeting_afternoon: 'Buenas tardes,',
    greeting_evening: 'Buenas noches,',
    tab_balance: 'Balance',
    tab_goals: 'Metas',
    tab_debts: 'Deudas',
    total_balance: 'Balance Total',
    my_accounts: 'Mis Cuentas',
    recent_activity: 'Movimientos',
    new_record: 'Nuevo Registro',
    add_account: 'Añadir Cuenta',
    add_goal: 'Añadir Meta',
    add_debt: 'Añadir Persona',
    edit_account: 'Editar Cuenta',
    edit_goal: 'Editar Meta',
    edit_debt: 'Editar Deuda',
    your_goals: 'Tus Objetivos',
    missing: 'Faltan',
    completed: 'Completado',
    owe_me: 'Me deben',
    i_owe: 'Debo',
    history: 'Historial',
    settings: 'Ajustes',
    welcome_title: 'Bienvenido a Cuentas Claras',
    name_placeholder: '¿Cómo te gustaría que te llamemos?',
    continue: 'Continuar',
    theme: 'Tema',
    language: 'Idioma',
    currency: 'Divisa Principal',
    search: 'Buscar...',
    no_transactions: 'No hay transacciones recientes',
    delete: 'Eliminar',
    save: 'Guardar',
    cancel: 'Cancelar',
    amount: 'Monto',
    concept: 'Concepto',
    description: 'Descripción (Opcional)',
    account: 'Cuenta',
    category: 'Categoría',
    type: 'Tipo',
    date: 'Fecha',
    income: 'Ingreso',
    expense: 'Gasto',
    transfer: 'Transferencia',
    debt_person: 'Persona',
    goal_name: 'Nombre de la Meta',
    target: 'Objetivo',
    feedback: 'Calificar App',
    notifications: 'Notificaciones',
    notify_low_balance: 'Balance Bajo',
    notify_debts: 'Recordatorio de Deudas',
    notify_goals: 'Hitos de Metas',
    threshold: 'Umbral',
    reports: 'Reportes',
    expenses_by_category: 'Gastos por Categoría',
    cat_salary: 'Salario',
    cat_freelance: 'Freelance',
    cat_gift: 'Regalo',
    cat_investment: 'Inversión',
    cat_food: 'Comida',
    cat_transport: 'Transporte',
    cat_utilities: 'Servicios',
    cat_entertainment: 'Entretenimiento',
    cat_shopping: 'Compras',
    cat_health: 'Salud',
    cat_education: 'Educación',
    cat_housing: 'Vivienda',
    cat_other: 'Otros',
    alert_low_balance: '¡Alerta de balance bajo!',
    alert_debt_due: 'Vencimiento de deuda cercano:',
    alert_goal_milestone: '¡Felicidades! Hito alcanzado:',
    view_list: 'Lista',
    view_chart: 'Gráfica',
    initial_balance: 'Balance Inicial',
    current_saved: 'Ahorrado Actual',
    deposit_to_goal: 'Depósito a Meta',
  },
  en: {
    greeting_morning: 'Good morning,',
    greeting_afternoon: 'Good afternoon,',
    greeting_evening: 'Good evening,',
    tab_balance: 'Balance',
    tab_goals: 'Goals',
    tab_debts: 'Debts',
    total_balance: 'Total Balance',
    my_accounts: 'My Accounts',
    recent_activity: 'Recent Activity',
    new_record: 'New Record',
    add_account: 'Add Account',
    add_goal: 'Add Goal',
    add_debt: 'Add Person',
    edit_account: 'Edit Account',
    edit_goal: 'Edit Goal',
    edit_debt: 'Edit Debt',
    your_goals: 'Your Goals',
    missing: 'Remaining',
    completed: 'Completed',
    owe_me: 'Owed to me',
    i_owe: 'I owe',
    history: 'History',
    settings: 'Settings',
    welcome_title: 'Welcome to Clear Accounts',
    name_placeholder: 'What should we call you?',
    continue: 'Continue',
    theme: 'Theme',
    language: 'Language',
    currency: 'Main Currency',
    search: 'Search...',
    no_transactions: 'No recent transactions',
    delete: 'Delete',
    save: 'Save',
    cancel: 'Cancel',
    amount: 'Amount',
    concept: 'Title',
    description: 'Description (Optional)',
    account: 'Account',
    category: 'Category',
    type: 'Type',
    date: 'Date',
    income: 'Income',
    expense: 'Expense',
    transfer: 'Transfer',
    debt_person: 'Person',
    goal_name: 'Goal Name',
    target: 'Target',
    feedback: 'Rate App',
    notifications: 'Notifications',
    notify_low_balance: 'Low Balance',
    notify_debts: 'Debt Reminders',
    notify_goals: 'Goal Milestones',
    threshold: 'Threshold',
    reports: 'Reports',
    expenses_by_category: 'Expenses by Category',
    cat_salary: 'Salary',
    cat_freelance: 'Freelance',
    cat_gift: 'Gift',
    cat_investment: 'Investment',
    cat_food: 'Food',
    cat_transport: 'Transport',
    cat_utilities: 'Utilities',
    cat_entertainment: 'Entertainment',
    cat_shopping: 'Shopping',
    cat_health: 'Health',
    cat_education: 'Education',
    cat_housing: 'Housing',
    cat_other: 'Other',
    alert_low_balance: 'Low balance alert!',
    alert_debt_due: 'Debt due soon:',
    alert_goal_milestone: 'Congrats! Goal milestone:',
    view_list: 'List',
    view_chart: 'Chart',
    initial_balance: 'Initial Balance',
    current_saved: 'Currently Saved',
    deposit_to_goal: 'Deposit to Goal',
  },
  fr: {
    greeting_morning: 'Bonjour,',
    greeting_afternoon: 'Bon après-midi,',
    greeting_evening: 'Bonsoir,',
    tab_balance: 'Solde',
    tab_goals: 'Objectifs',
    tab_debts: 'Dettes',
    total_balance: 'Solde Total',
    my_accounts: 'Mes Comptes',
    recent_activity: 'Activité Récente',
    new_record: 'Nouveau',
    add_account: 'Ajouter',
    add_goal: 'Ajouter Objectif',
    add_debt: 'Ajouter Personne',
    edit_account: 'Modifier Compte',
    edit_goal: 'Modifier Objectif',
    edit_debt: 'Modifier Dette',
    your_goals: 'Vos Objectifs',
    missing: 'Restant',
    completed: 'Terminé',
    owe_me: 'On me doit',
    i_owe: 'Je dois',
    history: 'Historique',
    settings: 'Réglages',
    welcome_title: 'Bienvenue',
    name_placeholder: 'Comment devons-nous vous appeler ?',
    continue: 'Continuer',
    theme: 'Thème',
    language: 'Langue',
    currency: 'Devise',
    search: 'Rechercher...',
    no_transactions: 'Aucune transaction',
    delete: 'Supprimer',
    save: 'Enregistrer',
    cancel: 'Annuler',
    amount: 'Montant',
    concept: 'Titre',
    description: 'Description',
    account: 'Compte',
    category: 'Catégorie',
    type: 'Type',
    date: 'Date',
    income: 'Revenu',
    expense: 'Dépense',
    transfer: 'Virement',
    debt_person: 'Personne',
    goal_name: 'Nom de l\'objectif',
    target: 'Cible',
    feedback: 'Noter l\'app',
    notifications: 'Notifications',
    notify_low_balance: 'Solde Bas',
    notify_debts: 'Rappel de Dettes',
    notify_goals: 'Étapes Objectifs',
    threshold: 'Seuil',
    reports: 'Rapports',
    expenses_by_category: 'Dépenses par Catégorie',
    cat_salary: 'Salaire',
    cat_freelance: 'Freelance',
    cat_gift: 'Cadeau',
    cat_investment: 'Investissement',
    cat_food: 'Nourriture',
    cat_transport: 'Transport',
    cat_utilities: 'Utilitaires',
    cat_entertainment: 'Divertissement',
    cat_shopping: 'Shopping',
    cat_health: 'Santé',
    cat_education: 'Éducation',
    cat_housing: 'Logement',
    cat_other: 'Autre',
    alert_low_balance: 'Alerte de solde bas !',
    alert_debt_due: 'Dette à payer bientôt :',
    alert_goal_milestone: 'Bravo ! Étape atteinte :',
    view_list: 'Liste',
    view_chart: 'Graphique',
    initial_balance: 'Solde Initial',
    current_saved: 'Actuellement épargné',
    deposit_to_goal: 'Dépôt sur Objectif',
  },
  pt: {
    greeting_morning: 'Bom dia,',
    greeting_afternoon: 'Boa tarde,',
    greeting_evening: 'Boa noite,',
    tab_balance: 'Saldo',
    tab_goals: 'Metas',
    tab_debts: 'Dívidas',
    total_balance: 'Saldo Total',
    my_accounts: 'Minhas Contas',
    recent_activity: 'Atividade Recente',
    new_record: 'Novo Registro',
    add_account: 'Adicionar Conta',
    add_goal: 'Adicionar Meta',
    add_debt: 'Adicionar Pessoa',
    edit_account: 'Editar Conta',
    edit_goal: 'Editar Meta',
    edit_debt: 'Editar Dívida',
    your_goals: 'Seus Objetivos',
    missing: 'Faltam',
    completed: 'Concluído',
    owe_me: 'Me devem',
    i_owe: 'Devo',
    history: 'Histórico',
    settings: 'Ajustes',
    welcome_title: 'Bem-vindo ao Contas Claras',
    name_placeholder: 'Como devemos chamá-lo?',
    continue: 'Continuar',
    theme: 'Tema',
    language: 'Idioma',
    currency: 'Moeda Principal',
    search: 'Buscar...',
    no_transactions: 'Sem transações recentes',
    delete: 'Excluir',
    save: 'Salvar',
    cancel: 'Cancelar',
    amount: 'Valor',
    concept: 'Título',
    description: 'Descrição',
    account: 'Conta',
    category: 'Categoria',
    type: 'Tipo',
    date: 'Data',
    income: 'Receita',
    expense: 'Despesa',
    transfer: 'Transferência',
    debt_person: 'Pessoa',
    goal_name: 'Nome da Meta',
    target: 'Alvo',
    feedback: 'Avaliar App',
    notifications: 'Notificações',
    notify_low_balance: 'Saldo Baixo',
    notify_debts: 'Lembrete de Dívidas',
    notify_goals: 'Marcos de Metas',
    threshold: 'Limite',
    reports: 'Relatórios',
    expenses_by_category: 'Despesas por Categoria',
    cat_salary: 'Salário',
    cat_freelance: 'Freelance',
    cat_gift: 'Presente',
    cat_investment: 'Investimento',
    cat_food: 'Comida',
    cat_transport: 'Transporte',
    cat_utilities: 'Utilidades',
    cat_entertainment: 'Entretenimento',
    cat_shopping: 'Compras',
    cat_health: 'Saúde',
    cat_education: 'Educação',
    cat_housing: 'Habitação',
    cat_other: 'Outros',
    alert_low_balance: 'Alerta de saldo baixo!',
    alert_debt_due: 'Dívida vencendo em breve:',
    alert_goal_milestone: 'Parabéns! Meta alcançada:',
    view_list: 'Lista',
    view_chart: 'Gráfico',
    initial_balance: 'Saldo Inicial',
    current_saved: 'Economizado Atual',
    deposit_to_goal: 'Depósito em Meta',
  }
};
